p1: problema1.tex
	pdflatex problema1.tex
	pdflatex problema1.tex

p2: problema2.tex
	pdflatex problema2.tex
	pdflatex problema2.tex

p3: problema3.tex
	pdflatex problema3.tex
	pdflatex problema3.tex

clean:
	rm -f *.aux *.log