p1: ejercicio1.tex
	pdflatex ejercicio1.tex
	pdflatex ejercicio1.tex

p2: ejercicio2.tex
	pdflatex ejercicio2.tex
	pdflatex ejercicio2.tex

p3: ejercicio3.tex
	pdflatex ejercicio3.tex
	pdflatex ejercicio3.tex

p4: ejercicio4.tex
	pdflatex ejercicio4.tex
	pdflatex ejercicio4.tex

p5: ejercicio5.tex
	pdflatex ejercicio5.tex
	pdflatex ejercicio5.tex

p6: ejercicio6.tex
	pdflatex ejercicio6.tex
	pdflatex ejercicio6.tex

p7: ejercicio7.tex
	pdflatex ejercicio7.tex
	pdflatex ejercicio7.tex

p8: ejercicio8.tex
	pdflatex ejercicio8.tex
	pdflatex ejercicio8.tex
clean:
	rm -f *.aux *.log