p1: ejercicio1.tex
	pdflatex ejercicio1.tex
	pdflatex ejercicio1.tex

p2: ejercicio2.tex
	pdflatex ejercicio2.tex
	pdflatex ejercicio2.tex

p3: ejercicio3.tex
	pdflatex ejercicio3.tex
	pdflatex ejercicio3.tex

p4: ejercicio4.tex
	pdflatex ejercicio4.tex
	pdflatex ejercicio4.tex

p5: ejercicio5.tex
	pdflatex ejercicio5.tex
	pdflatex ejercicio5.tex

clean:
	rm -f *.aux *.log