problem1: problem_1.tex
	pdflatex problem_1.tex
	pdflatex problem_1.tex

problem2: problem_2.tex
	pdflatex problem_2.tex
	pdflatex problem_2.tex

problem3: problem_3.tex
	pdflatex problem_3.tex
	pdflatex problem_3.tex
	
clean:
	rm -f *.aux *.log